name: pdmodels
channels:
  - schrodinger
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - jupyter=1.1.1
  - prody=2.4.1
  - pymol=3.1.3
  - python=3.11.11
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - biopython==1.84
      - biotite==0.41.2
      - biotraj==1.2.2
      - chex==0.1.88
      - contourpy==1.3.1
      - cycler==0.12.1
      - deepspeed==0.5.9
      - dm-haiku==0.0.13
      - dm-tree==0.1.8
      - docker==7.1.0
      - einops==0.8.0
      - etils==1.11.0
      - fair-esm==2.0.0
      - filelock==3.16.1
      - flatbuffers==24.12.23
      - flax==0.10.2
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - hjson==3.1.0
      - huggingface-hub==0.27.1
      - humanize==4.11.0
      - ihm==1.8
      - immutabledict==4.2.1
      - jax[cuda12]==0.4.38
      - jaxlib==0.4.38
      - jmp==0.0.4
      - joblib==1.4.2
      - keras==3.8.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.4.1
      - modelcif==1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - namex==0.0.8
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.6.85
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.13.1
      - orbax-checkpoint==0.11.0
      - pandas==2.2.3
      - propcache==0.2.1
      - protobuf==5.29.3
      - py-cpuinfo==9.0.0
      - py3dmol==2.4.2
      - pyparsing==3.2.1
      - regex==2024.11.6
      - rich==13.9.4
      - safetensors==0.5.2
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - seaborn==0.13.2
      - simplejson==3.19.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.71
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - toolz==1.0.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - tqdm==4.67.1
      - transformers==4.47.1
      - triton==3.1.0
      - tzdata==2024.2
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - yarl==1.18.3
      - pyg_lib==0.4.0+pt25cu124
      - torch_scatter==2.1.2+pt25cu124
      - torch_sparse==0.6.18+pt25cu124
      - torch_cluster==1.6.3+pt25cu124
      - torch_spline_conv==1.2.2+pt25cu124
      - -f https://data.pyg.org/whl/torch-2.5.0+cu124.html
      - git+https://github.com/google-deepmind/alphafold.git
      - git+https://github.com/aqlaboratory/openfold.git@pl_upgrades
