name: pdmodels
channels:
  - schrodinger
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - comm=0.2.2
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glew=2.1.0
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=10.1.0
  - hdf4=4.2.15
  - hdf5=1.14.4
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.31.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libdrm-cos7-x86_64=2.4.97
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglvnd-cos7-x86_64=1.0.1
  - libglvnd-glx-cos7-x86_64=1.0.1
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libholoplaycore=0.1.0_rc4
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=17.2
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mesa-libgl-cos7-x86_64=18.3.4
  - mesa-libglapi-cos7-x86_64=18.3.4
  - mistune=3.1.0
  - mpg123=1.32.9
  - mtz2ccp4_px=1.1
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.5
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.107
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - overrides=7.7.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - pmw=2.0.1+3
  - prody=2.4.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pymol=3.1.3
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rigimol=1.5
  - rpds-py=0.22.3
  - send2trash=1.8.3
  - setuptools=75.7.0
  - sip=6.7.12
  - six=1.17.0
  - slm_x509=2024.3
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - vtk-m=1.8.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - biopython==1.84
      - biotite==0.41.2
      - biotraj==1.2.2
      - chex==0.1.88
      - contourpy==1.3.1
      - cycler==0.12.1
      - deepspeed==0.5.9
      - dm-haiku==0.0.13
      - dm-tree==0.1.8
      - docker==7.1.0
      - einops==0.8.0
      - etils==1.11.0
      - fair-esm==2.0.0
      - filelock==3.16.1
      - flatbuffers==24.12.23
      - flax==0.10.2
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - hjson==3.1.0
      - huggingface-hub==0.27.1
      - humanize==4.11.0
      - ihm==1.8
      - immutabledict==4.2.1
      - jax[cuda12]==0.4.38
      - jaxlib==0.4.38
      - jmp==0.0.4
      - joblib==1.4.2
      - keras==3.8.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.4.1
      - modelcif==1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - namex==0.0.8
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.6.85
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.13.1
      - orbax-checkpoint==0.11.0
      - pandas==2.2.3
      - propcache==0.2.1
      - protobuf==5.29.3
      - py-cpuinfo==9.0.0
      - py3dmol==2.4.2
      - pyparsing==3.2.1
      - regex==2024.11.6
      - rich==13.9.4
      - safetensors==0.5.2
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - seaborn==0.13.2
      - simplejson==3.19.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.71
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - toolz==1.0.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - tqdm==4.67.1
      - transformers==4.47.1
      - triton==3.1.0
      - tzdata==2024.2
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - yarl==1.18.3
      - pyg_lib==0.4.0+pt25cu124
      - torch_scatter==2.1.2+pt25cu124
      - torch_sparse==0.6.18+pt25cu124
      - torch_cluster==1.6.3+pt25cu124
      - torch_spline_conv==1.2.2+pt25cu124
      - -f https://data.pyg.org/whl/torch-2.5.0+cu124.html
      - git+https://github.com/google-deepmind/alphafold.git
      # - git+https://github.com/aqlaboratory/openfold.git@pl_upgrades
