name: pdmodels
channels:
  - schrodinger
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - anyio=4.9.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attr=2.5.1
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - cyrus-sasl=2.1.28
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.13.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - glew=2.1.0
  - glib=2.84.0
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=11.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=2.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.4
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdeflate=1.23
  - libdrm=2.4.125
  - libdrm-cos7-x86_64=2.4.97
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglvnd-cos7-x86_64=1.0.1
  - libglvnd-glx-cos7-x86_64=1.0.1
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libholoplaycore=0.1.0_rc4
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.49
  - libpq=17.5
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mesa-libgl-cos7-x86_64=18.3.4
  - mesa-libglapi-cos7-x86_64=18.3.4
  - mistune=3.1.3
  - mpg123=1.32.9
  - mtz2ccp4_px=1.1
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.113
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - ply=3.11
  - pmw=2.0.1+3
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pymol=3.1.6.1
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rigimol=1.5
  - rpds-py=0.22.3
  - send2trash=1.8.3
  - sip=6.10.0
  - six=1.17.0
  - slm_x509=2024.3
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vtk-m=1.8.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - alphafold==2.3.2
      - alphafold3==3.0.1
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - biopython==1.85
      - biotite==1.3.0
      - biotraj==1.2.2
      - chex==0.1.89
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepspeed==0.17.1
      - dm-haiku==0.0.14
      - dm-tree==0.1.9
      - docker==7.1.0
      - einops==0.8.1
      - etils==1.12.2
      - fair-esm==2.0.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - flax==0.10.6
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - hjson==3.1.0
      - huggingface-hub==0.33.1
      - humanize==4.12.3
      - ihm==2.6
      - immutabledict==4.2.1
      - jax==0.6.2
      - jax-cuda12-pjrt==0.6.2
      - jax-cuda12-plugin==0.6.2
      - jax-triton==0.3.0
      - jaxlib==0.6.2
      - jaxtyping==0.2.34
      - jmp==0.0.4
      - joblib==1.5.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdtraj==1.11.0
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.1
      - modelcif==1.4
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.2
      - namex==0.1.0
      - networkx==3.5
      - ninja==1.11.1.4
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvshmem-cu12==3.3.9
      - nvidia-nvtx-cu12==12.8.55
      - openfold==2.2.0
      - opt-einsum==3.4.0
      - optax==0.2.5
      - optree==0.16.0
      - orbax-checkpoint==0.11.16
      - pandas==2.3.0
      - prody==2.5.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - py3dmol==2.5.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyg-lib==0.4.0+pt27cu128
      - pyparsing==3.1.1
      - rdkit==2024.3.5
      - regex==2024.11.6
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - setuptools==80.9.0
      - simplejson==3.20.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.19.0
      - tensorstore==0.1.75
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - toolz==1.0.0
      - torch==2.7.1+cu128
      - torch-cluster==1.6.3+pt27cu128
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cu128
      - torch-sparse==0.6.18+pt27cu128
      - torch-spline-conv==1.2.2+pt27cu128
      - torchaudio==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - tqdm==4.67.1
      - transformers==4.53.0
      - treescope==0.1.9
      - triton==3.3.1
      - typeguard==2.13.3
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uv==0.7.17
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.20.1
